### ISSUE TITLE
-lfreetype could not compile?

### ISSUE THREAD

**Issue by RoboMantis** [aochagavia/RusticMineSweeper#1]
I had a problem -lfreetype said could not compile?
This was on more than one computer running ubuntu and rust nightly
whats wrong with me!?

**Comment by aochagavia** [comment]
Could you provide more details about the error? I am afraid I cannot reproduce it with the information you gave me.

**Comment by RoboMantis** [comment]
i was using c9.io It doesn't allow display?

**Comment by aochagavia** [comment]
I don't know how c9.io works, but it seems like this problem is related to it. Therefore, I don't think there is anything I can do to fix it (so I am closing this issue).

Feel free to comment below if you manage to solve the problem
